### ISSUE TITLE
Better syntax for relative colors?

### ISSUE THREAD

**Issue by mirisuzanne** [mirisuzanne/blend#1]
See the current [CSS relative colors specification](https://www.w3.org/TR/css-color-5/#relative-RGB), for reference.

The first-draft syntax might be a bit too terse & esoteric?

```scss
// A rough interpretation of the Level 5 relative color syntax
$adjust: (
  blend.from($color, l, 20, h), // set chroma to 20
  blend.from($color, l, c, h -60), // linear adjustments to a channel
  blend.from($color, l 50%, c, h), // relative scale, e.g. "half-way to white"
  blend.from($color, 2l, c, h), // multiply the channel value
);
```

We probably also want a way to expand out this syntax to other color formats. We could try doing that in the individual color functions, as proposed for css – but that's a lot of extra parsing. Maybe something like individual `<format>-from()` functions, or a final `$format` argument?

**Comment by mirisuzanne** [comment]
CSS doesn't currently provide a built in relative-scale syntax, but we've found that to be the most useful form of color-adjustment in Sass…

**Comment by mirisuzanne** [comment]
More context. The current CSS proposal defines a syntax where `calc()` can access channel values, inside the adjustment for each channel.

```css
lch(from var(--color) l calc(c + 20) h)
```

Sass has no way to capture that sort of math equation, and compile it later with the proper channels (unless you capture a function, but that's pretty bulky).

Sass internal color module uses individual functions like `change()`, `adjust()`, and `scale()` for each type of color-adjustment, rather than having a unified syntax. I'm hoping we can find something that is both clear and concise.

**Comment by argyleink** [comment]
> Sass has no way to capture that sort of math equation, and compile it later with the proper channels (unless you capture a function, but that's pretty bulky).

can expressions be captured? 

`blend.from($color, l, (c + 20), h)`

**Comment by mirisuzanne** [comment]
The only way to capture an expression is:

1. write a function
2. capture that function
3. pass it in

That would look like:

```scss
@function add($channel, $scale) { @return $channel + $scale; };
$add: meta.get-function('add');

$relative: from($color, l, c, $add h 20); // with internal logic to call the function with arguments...
```

**Comment by una** [comment]
Hmm.. I know you already looked into this, but with Sass, can't we add/subtract without the `calc()` function? Can we interpolate the value this way? `blend.from($color, l, #{${c} + 20}, h)`

**Comment by mirisuzanne** [comment]
@una Sass can do the math just fine, but it does not have a way to capture that math equation until we're ready to replace the channel-name with an actual value. Sass will try to compile any math right away, so you can write e.g. `c + 20` as an argument, but the function just sees that as a concatenated string `c20`. The  `#{}` syntax  is also processed right away - so it doesn't help store a calculation to process internally.

**Comment by mirisuzanne** [comment]
Current plan is to keep the terse `from()` syntax, and also provide a more verbose functional syntax:

```scss
//  for relative color adjustments
$adjust: (
  // set chroma to 10
  blend.set($color, $chroma: 10),
  // adjust hue by -10
  blend.adjust($color, $hue: -10),
  // scale lightness 10% lighter
  blend.scale($color, $lightness: 10%),
);
```

**Comment by alolalo** [comment]
I don't have a technical answer for you but have been following along on Twitter about your progress regarding LCH, hope to give you an "angle" from an article I read; https://css-tricks.com/programming-sass-to-create-accessible-color-combinations/

My (false) take on this; Create a pre-calculated look-up table for the values, then process them

**Comment by mirisuzanne** [comment]
@alolalo That sounds like a solution for `contrast` specifically? And is probably better suited for a design system rather than a generic tool. Or am I missing something?

**Comment by alolalo** [comment]
Yes... someone who can help you figure this out because you helped me better than I helped you 🖖. Keep it up as what I'm taking note of from watching this; a perceptually & technically isometrical (equal) color contrast that unifies a "language of color" we can all learn from to apply and understand as designers & developers from a fundamentally correct p.o.v.

You could also turn what you're doing completely on it's head; how we used to apply and look at color only was technically correct, but not linguistically correct; the computer brain and the human brain both see a different color because it was designed for a computer to begin with. 

// Opinions & viewpoinnts are my own
The HSL vs LCH thing is to me almost the same problem as we have with "dark & light" vs "luminosity & contrast"; one is an abstraction of how things work, the other explains how things work and what it's main functions are that make it work. 

Why I use the definition "high-contrast theme" (dark) and "high-luminosity theme" is because that is actually what is happening when you switch; the canvas (background) changes it's function from being luminous and light, to being dark and full of contrast. Because in either theme it's just either luminosity painted on top of a canvas of contrast (dark mode), or contrast painted on top of canvas of luminosity if you look at it from pure black & white. 

Therefore all colors technically have contrast & luminosity, including black & white unlike many snobs say "they are not colors". **They are** because we can see them and identify them as colors right? We cant test if they have contrast right? They are pretty much the most used colors on the entire web right? 

No matter the order of color like white, black, and anything in between; the color-spectrum we can generate on a device is something we must uniformly understand to even get an understanding of the understanding we need to understand each other in the first place. Me included, that's why I'm here too to learn so don't be afraid to sound foolish; I'm a master at that so let me teach you  😂

**Comment by mirisuzanne** [comment]
Current plan is to keep the terse `from()` syntax, and also provide a more verbose functional syntax:

```scss
//  for relative color adjustments
$adjust: (
  // set chroma to 10
  blend.set($color, $chroma: 10),
  // adjust hue by -10
  blend.adjust($color, $hue: -10),
  // scale lightness 10% lighter
  blend.scale($color, $lightness: 10%),
);
```
